Ghafar-Tajhiz/Controllers/OrderController.cs
using BusinessLogic.BasketItemServices;
using BusinessLogic.BasketServices;
using Ghafar_Tajhiz.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ghafar_Tajhiz.Controllers
{
    public class OrderController : Controller
    {
        private readonly BasketService _basketService;
        private readonly BasketItemService _basketItemService;
        public OrderController(BasketService basketService, BasketItemService basketItemService)
        {
            _basketService = basketService;
            _basketItemService = basketItemService;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> AddToBasket([FromBody] AddBasketDto model)
        {
            if (model == null || model.qty <= 0)
                return BadRequest(new { res = false, msg = "اطلاعات نامعتبر است" });

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
                return Ok(new { res = false, msg = "شما لاگین نکرده‌اید" });

            var result = await _basketService.AddToBasket(
                model.productId,
                model.qty,
                Convert.ToInt32(userId)
            );

            if (!result)
                return Ok(new { res = false, msg = "خطا در افزودن به سبد خرید" });

            return Ok(new { res = true, msg = "محصول با موفقیت اضافه شد" });
        }

        [Authorize]
        public async Task<IActionResult> Basket()
        {
            var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);

            var data= await _basketService.GetUserBasket(Convert.ToInt32(userId));

            return View(data);
        }


        [HttpPost]
        public async Task<IActionResult> RemoveBasketItem([FromBody] RemoveBasketItemDto model)
        {
            var res = await _basketItemService.RemoveBasketItem(model.BasketItemId);
            return Ok(new { res = true });

        }

        [Authorize]
        public async Task<IActionResult> Pay(PayDto model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var data = await _basketService.Pay(model.mobile,model.address,Convert.ToInt32(userId));

            return RedirectToAction("Index","Profile");
        }

        public async Task<IActionResult> GetBasketCount()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Ok(0);   // not logged in -> empty basket

            // Assuming you have a service to get basket items
            var count = await _basketService.GetBasketItemCountAsync(Convert.ToInt32(userId));
            return Ok(count);
        }
    }
}

Ghafar-Tajhiz/Controllers/ProductController.cs
using BusinessLogic.BasketServices;
using BusinessLogic.CommentServices;
using BusinessLogic.ProductServices;
using DataAccess.Models;
using Ghafar_Tajhiz.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ghafar_Tajhiz.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly CommentService _commentService;
        private readonly UserManager<User> _userManager;
        public ProductController(ProductService productService, CommentService commentService, UserManager<User> userManager)
        {
            _productService = productService;
            _commentService = commentService;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(int id)
        {
            if (id <= 0)
                return BadRequest();

            var product = await _productService.GetProductById(id);

            if (product == null)
                return NotFound();

            return View(product);
        }

        public async Task<IActionResult> ProductList(int page = 1, int pageSize = 8, string search = null, string sort = "newest")
        {
            var data = await _productService.GetProductPagination(page, pageSize, search, sort);

            ViewBag.CurrentPage = data.Page;
            ViewBag.TotalPages = data.TotalPage;
            ViewBag.Search = search;
            ViewBag.Sort = sort;

            return View(data.Products);
        }
        public async Task<IActionResult> GetProduct(int id)
        {
            
            var product = await _productService.GetProductById(id);
            
            if (product == null)
                return NotFound();

            return PartialView(product);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProductComment([FromBody] AddCommentDto model)
        {
            if (model == null || string.IsNullOrWhiteSpace(model.text))
                return BadRequest(new { res = false, msg = "اطلاعات نامعتبر است" });

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return Unauthorized(new { res = false, msg = "شما لاگین نکرده‌اید" });

            var user = await _userManager.GetUserAsync(User);
            var userName = user.FullName;

            await _commentService.CreateComment(model.text, model.productId, userName);

            return Ok(new { res = true, msg = "نظر شما با موفقیت ثبت شد" });
        }
    }
}

Ghafar-Tajhiz/Views/Shared/_Layout.cshtml
@using DataAccess.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> _signInManager;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ghafar_Tajhiz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ghafar_Tajhiz.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <!-- SweetAlert2 JS -->
</head>
<body>

    <!-- Navbar -->
    <nav class="nav">
        <div class="mobilenavbar hidden">
            <a><i id="mobileNavbarBtn" class="fa fa-bars" aria-hidden="true"></i></a>
            <a><img width="100px" src="~/asstes/icon/Logo.svg" alt="Alternate Text" /></a>
            <a class="login-btn" asp-controller="Order" asp-action="Basket">
                سبد خرید
                <span id="cart-badge-mobile" class="cart-badge">0</span>
            </a>

            @if (_signInManager.IsSignedIn(User))
            {
                <a class="login-btn" asp-controller="Profile" asp-action="Index">پروفایل</a> <!-- دکمه ورود برای موبایل -->
                <a class="login-btn" asp-controller="Account" asp-action="Logout">خروج از حساب</a>
            }
            else
            {
                <a class="login-btn" asp-controller="Account" asp-action="Login">ورود/ثبت نام</a> <!-- دکمه ورود برای موبایل -->
            }


        </div>

        <div class="desktopnavbar" id="desktopnavbar">
            <a asp-controller="Home" asp-action="Index">صفحه اصلی</a>
            <a asp-controller="Product" asp-action="ProductList">محصولات</a>
            

            <a asp-controller="Order" asp-action="Basket">
                سبد خرید
                <span id="cart-badge-desktop" class="cart-badge">0</span>
            </a>

            @if(_signInManager.IsSignedIn(User))
            {
                <a class="login-btn" asp-controller="Profile" asp-action="Index">پروفایل</a> <!-- دکمه ورود برای دسکتاپ -->
                <a class="login-btn" asp-controller="Account" asp-action="Logout">خروج از حساب</a> 
            }
            else
            {
                <a class="login-btn"  asp-controller="Account" asp-action="Register">ورود/ثبت نام</a> <!-- دکمه ورود برای دسکتاپ -->
            }

            <a asp-controller="Home" asp-action="aboutUs">درباره ما</a>
            <a ><img width="100px" src="~/asstes/icon/Logo.svg" alt="Alternate Text" /></a>
        </div>
    </nav>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- Footer -->
    <footer class="footer">
        <div class="footer-container">

            <div class="footer-section about">
                <h3>درباره ما</h3>
                <p>
                    ما یک شرکت فناوری پیشرو هستیم که در زمینه طراحی و توسعه سامانه‌های وب و راهکارهای ابری فعالیت می‌کنیم. هدف ما توانمندسازی کسب‌وکارها با استفاده از فناوری‌های نوین است.
                </p>
            </div>

            <div class="footer-section links">
                <h3>لینک‌های مهم</h3>
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                    <li><a href="#">خدمات</a></li>
                    <li><a href="#">مقالات</a></li>
                    <li><a href="#">تماس با ما</a></li>
                </ul>
            </div>

            <div class="footer-section social">
                <h3>ما را دنبال کنید</h3>
                <div class="social-icons">
                    <a><img src="~/asstes/icon/icons8-facebook.svg" alt=""></a>
                    <a><img src="~/asstes/icon/icons8-whatsapp.svg" alt=""></a>
                    <a><img src="~/asstes/icon/icons8-instagram.svg" alt=""></a>
                </div>
            </div>

        </div>

        <div class="footer-bottom">
            <p>© ۱۴۰۴ شرکت شما. تمامی حقوق محفوظ است.</p>
        </div>
    </footer>

    <!-- Modal -->
    <div id="modal" class="modal">
        <div class="modal-content">
            <span id="closeModal" class="close">&times;</span>

            <div id="modalBody">

            </div>
        </div>
    </div>


</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
<script src="~/js/script.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)